# Noetron Studio — ML Pipeline Template
# Generated by: noetron_aiproj scaffold (machine_learning)
# Toggle to No-Code view to edit visually, or edit here directly.

from noetron_runtime.data import Ingestor, Preprocessor, Step
from noetron_runtime.model import Trainer
from noetron_runtime.experiment import AutoLogger
from sklearn.ensemble import RandomForestClassifier


def run_pipeline(source: str, target_col: str = "target"):
    # Stage 1: Ingest
    df = Ingestor(source).load()

    # Stage 2: Preprocess
    pre = Preprocessor([
        Step("drop_nulls"),
        Step("encode_labels"),
        Step("normalize", method="standard"),
    ])
    df = pre.run(df)

    # Stage 3: Split
    X_train, X_val, X_test, y_train, y_val, y_test = pre.train_val_test_split(
        df, target_col=target_col
    )

    # Stage 4: Train
    trainer = Trainer(RandomForestClassifier(n_estimators=100, random_state=42))
    metrics = trainer.fit_classify(X_train, y_train, X_val, y_val)

    return metrics


if __name__ == "__main__":
    import sys
    source = sys.argv[1] if len(sys.argv) > 1 else "data/train.csv"
    print(run_pipeline(source))
